# FILE TEMPLATE

#BROKER_URL: redis://secret@redis:6379/0
BROKER_URL: amqp://guest:guest@rabbitmq:5672
ECOMMERCE_API_ROOT: https://ecommerce.domain.cl/api/v2/
JWT_ISSUER: https://domain.cl/oauth2/
JWT_SECRET_KEY: secret-values
MAX_FULFILLMENT_RETRIES: 11
SAILTHRU:
    SAILTHRU_ABANDONED_CART_DELAY: 60
    SAILTHRU_ABANDONED_CART_TEMPLATE: null
    SAILTHRU_CACHE_TTL_SECONDS: 3600
    SAILTHRU_ENABLE: false
    SAILTHRU_ENROLL_TEMPLATE: null
    SAILTHRU_KEY: sailthru key here
    SAILTHRU_MINIMUM_COST: 100
    SAILTHRU_PURCHASE_TEMPLATE: null
    SAILTHRU_RETRY_ATTEMPTS: 6
    SAILTHRU_RETRY_SECONDS: 3600
    SAILTHRU_SECRET: sailthru secret here
    SAILTHRU_UPGRADE_TEMPLATE: null
SITE_OVERRIDES: null