name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build Docker image
        run: docker build . --file .github/Dockerfile --tag eoluchile/ecommerce-worker:${GITHUB_SHA} --tag eoluchile/ecommerce-worker:latest

      - name: Push
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
          docker push eoluchile/ecommerce-worker:${GITHUB_SHA}
          docker push eoluchile/ecommerce-worker:latest
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}